version: '3.8'

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/canario-marketplace-web:${IMAGE_TAG:-latest}
    container_name: canario_web_prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - canario_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  canario_network:
    external: true
